### ISSUE TITLE
执行这个命令时报错mvn clean install -DskipTests

### ISSUE THREAD

**Issue by xuanqiang** [streamxhub/streamx#130]
![image](https://user-images.githubusercontent.com/6870162/117240283-0abbb080-ae63-11eb-98d2-dce32dfb6f5c.png)
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.11.3:npm (npm install) on project streamx-console-service: Failed to run task: 'npm install' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)

**Comment by xuanqiang** [comment]
本机没有安装npm，只安了jdk1.8和maven项目执行的命令安装，大佬给解决一下问题吧

**Comment by wolfboys** [comment]
需要安装nodejs 然后执行:
mvn clean install -DskipTests -Denv=prod

**Comment by xuanqiang** [comment]
@wolfboys 请问一下安装nodejs的版本是多少

**Comment by wolfboys** [comment]
加我微信,拉你进群,和我的github id一样.

**Comment by ITBOX-ITBOY** [comment]
> 加我微信,拉你进群,和我的github id一样.
我要安装什么版本的nodejs呢，我现在安装的是v16版本，还是报同样的错误
