### ISSUE TITLE
文档中分享的streamx-console链接已经过期。

### ISSUE THREAD

**Issue by kirac** [streamxhub/streamx#174]
![image](https://user-images.githubusercontent.com/15170003/119306890-6ed0d800-bc9d-11eb-8066-17d5d2d330a2.png)
文档中分享的streamx-console链接已经过期，麻烦提供一下最新的链接。

**Comment by wolfboys** [comment]
https://github.com/streamxhub/streamx/releases/tag/v1.0.0 已提供

**Comment by kirac** [comment]
里面没有这个文件。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "streamxhub/streamx"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月24日(星期一) 下午3:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [streamxhub/streamx] 文档中分享的streamx-console链接已经过期。 (#174)





 
https://github.com/streamxhub/streamx/releases/tag/v1.0.0 已提供
