### ISSUE TITLE
[Bug] 任务提交报错

### ISSUE THREAD

**Issue by micsmile** [streamxhub/streamx#178]
LogType:taskmanager.err
LogLastModifiedTime:Tue May 25 02:29:25 +0800 2021
LogLength:1829
LogContents:
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/kzh/servers/hadoop-2.9.2/data/tmp/nm-local-dir/filecache/13/log4j-slf4j-impl-2.12.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/kzh/servers/hadoop-2.9.2/share/hadoop/common/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.flink.runtime.taskexecutor.TaskManagerRunner.runTaskManagerProcessSecurely(Lorg/apache/flink/configuration/Configuration;)V
	at org.apache.flink.yarn.YarnTaskExecutorRunner.runTaskManagerSecurely(YarnTaskExecutorRunner.java:93)
	at org.apache.flink.yarn.YarnTaskExecutorRunner.main(YarnTaskExecutorRunner.java:67)
1621880965499 Running java agent shutdown
1621880965499 Running periodic profiler (last run): com.streamxhub.streamx.plugin.profiling.profiler.CpuAndMemoryProfiler@33d512c1
1621880965502 Running periodic profiler (last run): com.streamxhub.streamx.plugin.profiling.profiler.ThreadInfoProfiler@639c2c1d
1621880965502 Running periodic profiler (last run): com.streamxhub.streamx.plugin.profiling.profiler.StacktraceCollectorProfiler@bcec361
1621880965503 Ran periodic profiler (last run): com.streamxhub.streamx.plugin.profiling.profiler.StacktraceCollectorProfiler@bcec361
1621880965503 Running periodic profiler (last run): com.streamxhub.streamx.plugin.profiling.profiler.StacktraceReporterProfiler@26794848
1621880965504 Closing reporter com.streamxhub.streamx.plugin.profiling.reporter.HttpReporter@2dd9525b
1621880965504 Closed reporter com.streamxhub.streamx.plugin.profiling.reporter.HttpReporter@2dd9525b
End of LogType:taskmanager.err.

**Comment by wolfboys** [comment]
去官网扫下面的二维码加群讨论,反馈问题
