### ISSUE TITLE
[Bug] bug title

### ISSUE THREAD

**Issue by Narcasserun** [streamxhub/streamx#181]
**StreamX Version**: 1.0.0
**JVM version** (`java -version`): 1.8
**OS version** (`uname -a` if on a Unix-like system):  centos7
Streamx cannot add the flinksql quick start task. In Hadoop 3. X environment, the application name will show that it is running, and the background log will report an error: java.lang.NoClassDefFoundError: org/apache/hadoop/security/token/delegation/web/DelegationTokenAuthenticator

**Comment by zhisheng17** [comment]
像是包冲突了

**Comment by wolfboys** [comment]
fixed.
