### ISSUE TITLE
[Bug] 运行任务数统计不准确

### ISSUE THREAD

**Issue by lizhitao0923** [streamxhub/streamx#186]
**StreamX Version**:

**JVM version** (`java -version`): 1.8

**OS version** (`uname -a` if on a Unix-like system):

**问题概要**:  界面统计的 Runing Job 与真实运行的 Job 数量不一致

**重现过程**: 

描述问题能复现的整个过程

1. 创建 Flink SQL 任务，Flink SQL 任务中有两个 insert into TBL_XX
2. 提交任务运行，实际一个 application 有两个 Job，界面统计显示仅有一个 Job

**错误日志**:
无

**Comment by lizhitao0923** [comment]
![image](https://user-images.githubusercontent.com/6852212/120417538-9573ca80-c391-11eb-8231-42b657ce9660.png)
![image](https://user-images.githubusercontent.com/6852212/120417585-a7ee0400-c391-11eb-8687-a2cf838feb74.png)

**Comment by wolfboys** [comment]
已确认,待修复

**Comment by zhisheng17** [comment]
统计的维度是按照 yarn application id 的数量来统计的吧？

**Comment by wolfboys** [comment]
fixed.
