### ISSUE TITLE
[Bug] streamx-parent 中部分maven依赖在中央仓库找不到，无法下载，建议修改

### ISSUE THREAD

**Issue by Hermesfuxi** [streamxhub/streamx#204]
**问题概要**: 
依赖问题：在maven中央仓库找不到对应的依赖
### 1、vertx-lang-scala
在 https://mvnrepository.com/artifact/io.vertx/vertx-lang-scala 中找不到如下依赖：
![image](https://user-images.githubusercontent.com/18678070/123216388-0f642300-d4fc-11eb-96dc-3de60ba420fa.png)
建议改成
```
<!-- https://mvnrepository.com/artifact/io.vertx/vertx-lang-scala -->
<dependency>
    <groupId>io.vertx</groupId>
    <artifactId>vertx-lang-scala_2.12</artifactId>
    <version>3.8.5</version>
</dependency>
```
### 2、flink-connector-filesystem
同样的，在 https://mvnrepository.com/artifact/org.apache.flink/flink-connector-filesystem 中找不到如下依赖：
![image](https://user-images.githubusercontent.com/18678070/123216685-64a03480-d4fc-11eb-971b-9b8e842f88f2.png)

建议改成
```
<!-- https://mvnrepository.com/artifact/org.apache.flink/flink-connector-filesystem -->
<dependency>
    <groupId>org.apache.flink</groupId>
    <artifactId>flink-connector-filesystem_2.11</artifactId>
    <version>1.11.3</version>
</dependency>
```

**Comment by wolfboys** [comment]
fixed.
