### ISSUE TITLE
flinksql方式从kafka中导入数据到hive 作业无法执行

### ISSUE THREAD

**Issue by zhangxiao696** [streamxhub/streamx#219]
CREATE TABLE kafka_input(
    id BIGINT,
    name STRING,
    event_time STRING,
    num BIGINT
) 
WITH (
    'connector' = 'kafka',
    'topic' = 'xiao_test_1',
    'properties.bootstrap.servers' = 'xxxxx:9092',
    'properties.group.id' = 'testGroup',
    'scan.startup.mode' = 'latest-offset',
    'format' = 'json'
);

CREATE CATALOG myhive WITH (
    'type' = 'hive',
    'default-database' = 'xiao_test_1',
    'hive-conf-dir' = '/home/work/hive/hive/conf/'
);

SET table.sql-dialect=hive;

INSERT INTO stg_test_hive_table 
SELECT
    id,
    name as name_desc,
    event_time,
    num,
    CAST(TO_DATE(CAST(LOCALTIMESTAMP AS VARCHAR)) AS VARCHAR) as dt  
FROM kafka_input;

<img width="875" alt="图片" src="https://user-images.githubusercontent.com/13326803/124255553-e0355d80-db5c-11eb-9b14-8e0c8024f1b5.png">

<img width="1370" alt="图片" src="https://user-images.githubusercontent.com/13326803/124255629-f3e0c400-db5c-11eb-9cde-c59fca80c517.png">

请问这是什么情况？

**Comment by CecilHarvey** [comment]
原因是由于使用了jdk11
换用jdk8就可以了

**Comment by phillip2019** [comment]
> 原因是由于使用了jdk11 换用jdk8就可以了

请问对应的pom配置和sql怎么写的?

**Comment by phillip2019** [comment]
> CREATE TABLE kafka_input( id BIGINT, name STRING, event_time STRING, num BIGINT ) WITH ( 'connector' = 'kafka', 'topic' = 'xiao_test_1', 'properties.bootstrap.servers' = 'xxxxx:9092', 'properties.group.id' = 'testGroup', 'scan.startup.mode' = 'latest-offset', 'format' = 'json' );
> 
> CREATE CATALOG myhive WITH ( 'type' = 'hive', 'default-database' = 'xiao_test_1', 'hive-conf-dir' = '/home/work/hive/hive/conf/' );
> 
> SET table.sql-dialect=hive;
> 
> INSERT INTO stg_test_hive_table SELECT id, name as name_desc, event_time, num, CAST(TO_DATE(CAST(LOCALTIMESTAMP AS VARCHAR)) AS VARCHAR) as dt FROM kafka_input;
> 
> <img alt="图片" width="875" src="https://user-images.githubusercontent.com/13326803/124255553-e0355d80-db5c-11eb-9b14-8e0c8024f1b5.png">
> 
> <img alt="图片" width="1370" src="https://user-images.githubusercontent.com/13326803/124255629-f3e0c400-db5c-11eb-9cde-c59fca80c517.png">
> 
> 请问这是什么情况？

请问这个解决了吗，如何解决的?

**Comment by phillip2019** [comment]
已解决，配置文件缺失metastore.uri，添加上即可

**Comment by yixinGod** [comment]
请问streamx如何使用创建的 catalog，
执行 set catalog myhive 报sql解析错
![image](https://user-images.githubusercontent.com/19711685/154639984-2d0c806f-e728-4180-afb4-5abef72d2e2a.png)

**Comment by rcf666** [comment]
> 请问streamx如何使用创建的 catalog， 执行 set catalog myhive 报sql解析错 ![image](https://user-images.githubusercontent.com/19711685/154639984-2d0c806f-e728-4180-afb4-5abef72d2e2a.png)

请问这个问题解决了吗 我创建hivecatelog报这个错
![image](https://user-images.githubusercontent.com/57984361/178237088-716a67f6-209e-40e5-8721-a63dbc7b7b7a.png)

**Comment by yixinGod** [comment]
> 

![image](https://user-images.githubusercontent.com/19711685/178238787-70a54ccd-b1f6-483a-a3c9-d9489eac02ff.png)
完整的大概是这样，我用的是1.2.1的版本

**Comment by rcf666** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/19711685/178238787-70a54ccd-b1f6-483a-a3c9-d9489eac02ff.png) 完整的大概是这样，我用的是1.2.1的版本



> > 
> 
> ![image](https://user-images.githubusercontent.com/19711685/178238787-70a54ccd-b1f6-483a-a3c9-d9489eac02ff.png) 完整的大概是这样，我用的是1.2.1的版本

谢谢老哥  能加个微信吗 还有点问题

**Comment by growJie** [comment]
> > 请问streamx如何使用创建的 catalog， 执行 set catalog myhive 报sql解析错 ![image](https://user-images.githubusercontent.com/19711685/154639984-2d0c806f-e728-4180-afb4-5abef72d2e2a.png)
> 
> 请问这个问题解决了吗 我创建hivecatelog报这个错 ![image](https://user-images.githubusercontent.com/57984361/178237088-716a67f6-209e-40e5-8721-a63dbc7b7b7a.png)

请问一下，这个问题你解决了吗？我现在也遇到了
