### ISSUE TITLE
[Feat] Supports uploading jar type job

### ISSUE THREAD

**Issue by e-crown** [streamxhub/streamx#237]
导入project项目的时候使用git拉取项目代码的方式挺好 ，就是能不能增加一个直接上传可执行jar的方式呢，期待ing...

**Comment by CecilHarvey** [comment]
+1

having to use git prevents us from eg. providing only binaries to our clients.

**Comment by rayest** [comment]
+1

It will be much better if the JAR can be uploaded directly. 
Hoping......

**Comment by zhiyuan192shine** [comment]
+1

**Comment by wolfboys** [comment]
It's already in the plan. the next small version will be support
