### ISSUE TITLE
[Bug] 问题标题

### ISSUE THREAD

**Issue by e-crown** [streamxhub/streamx#238]
**StreamX Version**:
main
**JVM version** (`java -version`):
1.8.0_291
**OS version** (`uname -a` if on a Unix-like system):
Linux  3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**问题概要**:
     打包后的可部署执行文件中，bin/startup.sh 脚本中缺少$RUNJAVA变量的定义
**重现过程**:
   打开bin/startup.sh 脚本 ，查看$RUNJAVA变量
描述问题能复现的整个过程

1.
2.
3.

**错误日志**:
**[StreamX] ERROR: java is not install,please install java first!**

**Comment by wolfboys** [comment]
thanks for your report. It looks like a bug. need to be fixed
