### ISSUE TITLE
[Bug] 'salt' should be redacted in signin response.

### ISSUE THREAD

**Issue by CecilHarvey** [streamxhub/streamx#240]
**StreamX Version**: 1.1.0

**JVM version** (`java -version`): 1.8.0

**OS version** (`uname -a` if on a Unix-like system):
Fedora 34
Linux localhost.localdomain 5.13.1_palladium-1000.fc34.x86_64 #1 SMP PREEMPT Wed Jul 7 19:16:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Description of the problem including expected versus actual behavior**:

'salt' is included in the response of signin request, which should be redacted as the 'salt' is used to provide more security of the hashed password which should NOT be leaked.

{"data":{"user":{....., **"salt":"ats6sdxdqf8vsqjtz0utj461wr"**, ......},"status":"success"}

**Steps to reproduce**:

visit streamx in browser and signin. check the response in browser's devtools.

**Comment by wolfboys** [comment]
Thanks for your report.I agree with you.  'salt'  should not be leaked.
