### ISSUE TITLE
[Bug] 使用java api 构建kafkaSource时指定Topic报错

### ISSUE THREAD

**Issue by 1353297670** [streamxhub/streamx#242]
**StreamX Version**:1.1.0

**JVM version** (`java -version`):1.8

**OS version** (`uname -a` if on a Unix-like system):

**Description of the problem including expected versus actual behavior**:When using java api to build kafkaSource, specify the topic to report an error

**Steps to reproduce**:

val topicList = topic match {
          case null => topics.toList
          case x: String => List(x)
          case x: List[String] => x
          case _ => throw new IllegalArgumentException("[StreamX] topic type must be String(one topic) or List[String](more topic)")
        }
The topics in the custom Kafka Source<T> are array types, and there is no matching type when parsing
This is my solution：
val topicList = topic match {
          case null => topics.toList
          case x: String => List(x)
          case x: Array[String] => x.toList
          case x: List[String] => x
          case _ => throw new IllegalArgumentException("[StreamX] topic type must be String(one topic) or List[String](more topic)")
        }

**Stack Trace (if you have one)**:
Exception in thread "main" java.lang.IllegalArgumentException: [StreamX] topic type must be String(one topic) or List[String](more topic)
	at com.streamxhub.streamx.flink.core.scala.source.KafkaSource$.getSource(KafkaSource.scala:77)
	at com.streamxhub.streamx.flink.core.scala.source.KafkaSource.getSource(KafkaSource.scala)
	at com.streamxhub.streamx.flink.core.java.source.KafkaSource.getDataStream(KafkaSource.java:86)

**Comment by wolfboys** [comment]
this problem remains to be determined. If you want to specify topic, you must specify it before call getDatastream. please provide your code  @ 1353297670

**Comment by 1353297670** [comment]
This is my code,Please help to take a look  @wolfboys
       kafka.source:
          bootstrap.servers: 
          topic: test

        StreamEnvConfig envConfig = new StreamEnvConfig(args, null);
        StreamingContext streamingContext = new StreamingContext(envConfig);
        ExecutionConfig config = streamingContext.getJavaEnv().getConfig();
        KafkaSource kafkaSource = new KafkaSource(streamingContext).topic("test").deserializer(new 
                                                   ProtoKafkaDeserializationSchema());
        DataStreamSource kafkaSourceDataStream = kafkaSource.getDataStream();
        streamingContext.start();

**Comment by wolfboys** [comment]
it's a bug, you can fix it, welcome to submit pr.
