### ISSUE TITLE
[Bug] flinkSql verify bug

### ISSUE THREAD

**Issue by zhuangxiang** [streamxhub/streamx#265]
环境如下：
StreamX Version: 1.1.1
JVM version (`java -version`):1.8.0_172
OS version:centos7
flink version:flink 1.12.0

Bug Description：
修改flink sql过程中 flinkSql verify接口没有响应，不会提示sql语法错误，且无法提交sql修改

How to Reproduce
1. 进入streamx-application,修改flink sql任务
2. flink sql 编辑器对sql语句进行修改，触发flinkSql verify校验，接口超时不返回
3. 多次修改sql语句后，会导致服务器cpu使用率上升
![1df27b05206857bf99cb972768a0ce8](https://user-images.githubusercontent.com/31985626/127276543-7a74ba31-9247-4866-a69f-91bb3c6b840c.png)

streamx-线程
![5fadf7cce2228926353ed784b573f1f](https://user-images.githubusercontent.com/31985626/127275156-de9b6e13-b96b-40dd-9f2b-e70a30e2955e.png)
线程-59  堆栈信息
![f7cf04cc0fc01ff93989bb51275b546](https://user-images.githubusercontent.com/31985626/127275171-71adab4f-a077-41da-9021-9016d241cb1f.png)

Requirement or improvement
SqlCommandParser类parseLine 方法，第82行
val line = scanner.nextLine().replaceAll("--(.*)$|\\/*(.*)*\\/$", "").trim("")，使用正则替换注释存在性能问题。会引起服务器cpu飙升

**Comment by Al-assad** [comment]
@zhuangxiang 
The cpu cost of this part is indeed a bit high, perhaps the following optimizations cloud be made:
* perform `Pattern.compile(regex)` for regex expression and share it.
* remove the non-essential use of `matcher.replaceAll` or `string.replaceAll`. e.g. sql comment line can be removed directly from  which matching `string.trim.startWith(prefix)`.

Welcome to submit the relevant PR for further discuss the code implementation. Let's make this project better together.😃

**Comment by wolfboys** [comment]
fixed. thank your report.

已经修复, 感谢反馈,之前主要是解决with参数必须带引号问题,如: "bootstrap.server" = "192.168.0.0", 目的是做到可以不用带引号也可以( bootstrap.server = 192.168.0.0 ),所以会一行行的解析识别,得识别注释部分,后发现这块实现还比较复杂,不能简单的判断注释的开始位置,正则提取也会带来一些性能的开销.所以已经放弃这部分的优化
