### ISSUE TITLE
stramx 能否支持在进行开发的时候能否支持windows 环境？

### ISSUE THREAD

**Issue by a120610114** [streamxhub/streamx#293]
我按照官方文档进行项目部署，进行本地开发的时候经常会遇到很多奇怪的问题。
![image](https://user-images.githubusercontent.com/26463863/130943549-eb9d8632-8b61-4464-bfdd-d604de28fadf.png)
sql 校验一直不通过，明明sql 没有问题：

**Comment by wolfboys** [comment]
已确定这块设计有缺陷.解决多版本flink支持新带来的问题,flink多版本支持的相关功能在重构中...

**Comment by wolfboys** [comment]
cc @a120610114  这个pr在系统性的修复该问题:  https://github.com/streamxhub/streamx/pull/296

**Comment by a120610114** [comment]
> cc @a120610114 这个pr在系统性的修复该问题: #296

好的，多谢！修复后 等你们通知
