### ISSUE TITLE
flink sql 上传jar包失败

### ISSUE THREAD

**Issue by a120610114** [streamxhub/streamx#299]
StreamX Version:1.1.0
flink :1.13 
当我创建了一个flink 任务的时候，点击提交。结果成功，但是后面当我点击编辑想要再重新上传一下jar包的时候报错了
![image](https://user-images.githubusercontent.com/26463863/131432516-ba6aadc7-03ff-46c7-8f4c-6f1c45e82164.png)
当是我上传的就是一个jar包

**Comment by wolfboys** [comment]
浏览器信息,版本也附上,可能在某些特定的浏览器下,判断文件类型会有问题

**Comment by a120610114** [comment]
![image](https://user-images.githubusercontent.com/26463863/131433758-380cafbb-214f-48df-8306-c33d910f6a5e.png)
我使用的是谷歌浏览器 92.0.4515.107

**Comment by wolfboys** [comment]
fixed.
