### ISSUE TITLE
[Question] 创建任务，上传依赖jar，后台ApplicationController的upload接收的文件一直为空？

### ISSUE THREAD

**Issue by zuoinlv** [streamxhub/streamx#302]
![image](https://user-images.githubusercontent.com/3855382/131527892-fab641b5-d7b5-4c6d-bd43-5cf9f19d4a47.png)
这个方法接收的file一直为null，是为什么

**Comment by wolfboys** [comment]
fixed

**Comment by zuoinlv** [comment]
咋fixed，改了哪里，能告知一下吗
