### ISSUE TITLE
[Bug] 报警邮箱修改后需要重启才生效

### ISSUE THREAD

**Issue by zhangjun0x01** [streamxhub/streamx#306]
*请在提交你的 issue 前，请回答以下问题，这有助于社区快速定位问题，谢谢！ 🙏*

### Environment Description（运行环境描述）
* **StreamX Version**: 1.1.0
* **JVM version** (`java -version`): 8
* **OS version** (`uname -a` if on a Unix-like system): centos

### Bug Description（Bug 描述）
修改了发送报警的邮箱后，未生效，需要重启才生效。
此外，建议添加一个报警邮箱是否可用的测试按钮

### How to Reproduce（如何重现这个 Bug） 
重现 Bug 现场的步骤，比如：

### Additional context（额外的上下文信息）
添加额外有助于描述该问题的上下文信息，如 JVM 堆栈日志等

### Requirement or improvement（诉求 & 改进建议）
- 请描述您的诉求，或者对此的改进建议

**Comment by wolfboys** [comment]
thank you report...
