### ISSUE TITLE
期望支持任务调度功能

### ISSUE THREAD

**Issue by a120610114** [streamxhub/streamx#317]
在我们使用Flink 进行任务提交的时候，我们发现，不一定所有的任务都是流式的、持久的。也有很多时候它是批式处理的、而且具有一定的任务执行顺序。
因此我觉得，如果Streamx 能够集成 一个任务调度功能会非常的办。类似azKAban之类的

**Comment by Al-assad** [comment]
Thank for your suggestion, Support for Task Scheduling is a common need. We will plan it next, if you have some ideas about this, welcome to join in the development of StreamX.
See another issue: https://github.com/streamxhub/streamx/issues/198
