### ISSUE TITLE
[Bug] 前端看不到build log

### ISSUE THREAD

**Issue by glacierck** [streamxhub/streamx#322]
### Environment Description（运行环境描述）
* **StreamX Version**: 
* **JVM version** (`java -version`):1.8
* **OS version** (`uname -a` if on a Unix-like system):centos7

### Bug Description（Bug 描述）
在前端点击project build ，在弹出的日志窗口中是空的。后台输出监听没有报错。奇怪的是，最后后台输出了build成功，但前端还是看不到日志信息。
![image](https://user-images.githubusercontent.com/21599896/134873231-29dcd76c-8a00-4ac8-af31-72d53837290f.png)

![image](https://user-images.githubusercontent.com/21599896/134873278-7f25d6b9-9aca-4bae-bcd0-4605358256cb.png)

**Comment by liumingchao** [comment]
I have a similar problem
