### ISSUE TITLE
[License] Please keep Flink NOTICE file

### ISSUE THREAD

**Issue by CalvinKirs** [streamxhub/streamx#445]
As far as I know, this `com.streamxhub.streamx.common.domain.FlinkMemorySize` is completely copied from Apache Flink. According to AL2, you should keep NOTICE and LICENSE files.

**Comment by zhongjiajie** [comment]
Yeah, you're right

**Comment by Al-assad** [comment]
Indeed.

**Comment by wolfboys** [comment]
thank u, we are improving.
