### ISSUE TITLE
[Bug] get flink version bug

### ISSUE THREAD

**Issue by jlon** [streamxhub/streamx#447]
*请在提交你的 issue 前，请回答以下问题，这有助于社区快速定位问题，谢谢！ 🙏*

### Environment Description（运行环境描述）
* **StreamX Version**:  1.2.0
* **JVM version** (`java -version`): java8
* **OS version** (`uname -a` if on a Unix-like system):

### Bug Description（Bug 描述）
请简要、清晰地对您遇到的 Bug 进行描述。
![Image_20211118185908](https://user-images.githubusercontent.com/12132742/142403287-089c993a-bff1-4677-8c72-e43c69c6acd1.png)

**Comment by wolfboys** [comment]
你好,这个是获取flink version失败导致的,可以往上看看关于获取version这块有何报错信息.这个不是关键错误.

**Comment by lvshaokang** [comment]
I can try this issue，could you assign it to me?

**Comment by wolfboys** [comment]
ok. very good! 👍 😊 😌
