### ISSUE TITLE
[Bug] hadoop-user-name not work

### ISSUE THREAD

**Issue by DustinChan** [streamxhub/streamx#449]
*请在提交你的 issue 前，请回答以下问题，这有助于社区快速定位问题，谢谢！ 🙏*

### Environment Description（运行环境描述）
* **StreamX Version**: 1.2
* **JVM version** (`java -version`): 1.8
* **OS version** (`uname -a` if on a Unix-like system): centos 7.5

### Bug Description（Bug 描述）
修改配置文件application.yml 中的 hadoop-user-name 不生效，源码中没有引用到这个配置
![1637309823(1)](https://user-images.githubusercontent.com/18400439/142588928-e5108eb3-40a6-4abd-b4b3-5cfc86f3df15.png)

### Requirement or improvement（诉求 & 改进建议）
增加对这个配置的使用，

**Comment by monrg** [comment]
我对执行此任务感兴趣

**Comment by wolfboys** [comment]
very good. 👍 😊 😌
