### ISSUE TITLE
flinksql 以kafka作为数据源，部署时报错

### ISSUE THREAD

**Issue by VSMDD** [streamxhub/streamx#450]
## 常规问题（General Question）
按照官网提供的说明添加依赖，提交后报错，这个问题应该如何解决，如下图所示
![image](https://user-images.githubusercontent.com/31095506/142603493-fce24fdb-5cae-46e3-be1d-3027c17d8c8e.png)
![image](https://user-images.githubusercontent.com/31095506/142603604-ba2dbccf-5422-4516-ab41-e34f04e3e767.png)

**Comment by wolfboys** [comment]
这是没有在本地安装streamx吧?这两天把streamx相关的jar打到maven中央仓库就可以了.

**Comment by VSMDD** [comment]
> 是不是在本地安装streamx吧？这聪明把streamx相关的罐子打到maven中央仓库就可以了。另外这个地方不需要显示日期streamx的罐子

整了半天原来是因为这个多余的jiar包，非常感谢

**Comment by wolfboys** [comment]
现在可以了吗？
