### ISSUE TITLE
[Bug] When submitting with custom code, an error is reported due to the lack of dependent classes

### ISSUE THREAD

**Issue by waywtdcc** [streamxhub/streamx#464]
*Please answer these questions before submitting your issue. Thanks!*

### Environment Description
* **StreamX Version**: 1.1.0
* **JVM version** (`java -version`): 1.8
* **OS version** (`uname -a` if on a Unix-like system):

### Bug Description
Create a Flink project. There are two jar packages packaged under the project, one with dependent jar and one without dependent native jar package. When you select a jar package, you can only see the native jar package without dependency, resulting in an error for lack of dependency.

**Comment by wolfboys** [comment]
I don't understand what you mean. You can give a specific example to illustrate.
