### ISSUE TITLE
[Bug]  Unable to add role

### ISSUE THREAD

**Issue by hackallan** [streamxhub/streamx#467]
*Please answer these questions before submitting your issue. Thanks!*

### Environment Description
* streamx is the latest code
* java version "1.8.0_131"
* x86_64 x86_64 x86_64 GNU/Linux

### Bug Description
when i  add a new role, can not  submit 
![image](https://user-images.githubusercontent.com/18672845/143214725-44e45fbb-2096-4986-80e3-6c4dca66c321.png)

### How to Reproduce 
1、Role Management page ，new role 

### Requirement or improvement

- hope to fix this issue

**Comment by monrg** [comment]
I'm interested in that

**Comment by wolfboys** [comment]
> 
good job!
