### ISSUE TITLE
[Bug] yarn 提交任务 报错找不到 streamx-flink-sqlclient-1.2.1.jar

### ISSUE THREAD

**Issue by daixiaoyu** [streamxhub/streamx#468]
*请在提交你的 issue 前，请回答以下问题，这有助于社区快速定位问题，谢谢！ 🙏*

### Environment Description（运行环境描述）
* **StreamX Version**: 1.2.1
* **JVM version** (`java -version`):1.8
* **OS version** (`uname -a` if on a Unix-like system): mac os

### Bug Description（Bug 描述）
使用yarn提交任务后，始终不能找到入口，找不到jar包，如图
![image](https://user-images.githubusercontent.com/10663476/143240674-6bdd9a88-068f-4f60-8732-ef4c172fd1fe.png)
![image](https://user-images.githubusercontent.com/10663476/143240867-738152d2-d0a7-4f66-8794-f1389e873eef.png)

### How to Reproduce（如何重现这个 Bug） 
重现 Bug 现场的步骤，比如：
1、使用yarn提交任务

### Additional context（额外的上下文信息）
`JAR file does not exist '/private/tmp/hadoop-gump/nm-local-dir/usercache/hdfs/appcache/application_1637735783203_0008/container_1637735783203_0008_01_000001/streamx-flink-sqlclient-1.2.1.jar'`

### Requirement or improvement（诉求 & 改进建议）
- 希望可以得到回复，多谢。项目非常棒

**Comment by wolfboys** [comment]
fixed.
