### ISSUE TITLE
project deploy chosing a wrong jar(actually i need the fat jar)

### ISSUE THREAD

**Issue by gitfortian** [streamxhub/streamx#471]
*Please answer these questions before submitting your issue. Thanks!*

### Environment Description
* **StreamX Version**: 
* **JVM version** (`java -version`):
* **OS version** (`uname -a` if on a Unix-like system):

### Bug Description
project deploy chosing a wrong jar(actually i need the fat jar)

### How to Reproduce 
Steps to reproduce the behavior, for example:

1. Go to 'application'
2. Click on 'new a application' and submit
3.not the fat jar be moved to the deploy target directory

### Additional context
Add any other context about the problem here such as JVM track stack log.

### Requirement or improvement

- Please describe about your requirements or improvement suggestions.

**Comment by gitfortian** [comment]
i'm intersted in the issue

**Comment by wolfboys** [comment]
> i'm intersted in the issue

ok
