### ISSUE TITLE
[Bug] add user no description  &delete user can't work

### ISSUE THREAD

**Issue by monrg** [streamxhub/streamx#478]
* **StreamX Version**: 1.2.0
* **JVM version** (`java -version`):1.8.0

### Bug Description
 delete user err
![image](https://user-images.githubusercontent.com/45427129/143839669-8c78215a-5e2e-4ee0-a091-6bec9f58ea1e.png)

### How to Reproduce 
Steps to reproduce the behavior, for example:
1 add user
2 delete user

**Comment by monrg** [comment]
I will fix this bug

**Comment by wolfboys** [comment]
> I will fix this bug
> 
> 
> 
> 

good job！
