### ISSUE TITLE
[Question] Release v1.2.0  Modify the source code and start the job after the Project is compiled. It is found that the Flink mirror or custom package is not updated, and the job still executes the old jar

### ISSUE THREAD

**Issue by xinzhuxiansheng** [streamxhub/streamx#492]
## General Question

在测试 FLink on Kubernetes Application Mode 提交作业时，发现程序的jar执行的是老的jar， 发现的过程是我修改了
```java
env.execute("yzhou consumer");
```
在Flink UI上，仍然显示的是 老的name值。 
此时，为了见证是Maven ，还是镜像 或者还是checkpoint的问题， 我首先将镜像删除了，然后我将源码中的聚合工程的module的版本由1.0-SNAPSHOT，改成了 1.0.1-SNAPSHOT。 我准备重新再 作业选择执行的jar时， 页面表单不让我修改， 体现在以下2个方面：

1. 表单Module：无法选择 1.0.1-SNAPSHOT
2. 选择 Program Jar： 无法选择1.0.1-SNAPSHOT的jar

目前为啥Flink 运行的是老的jar，正在排查中 ，在页面上无法更改，提了此issue

**Comment by WilsonWangCS** [comment]
please add the param ```-Dkubernetes.container.image.pull-policy=Always```  into  ```Dynamic Option```. otherwise , the k
8s  would not pull the last version from docker responsitory.

**Comment by xinzhuxiansheng** [comment]
> please add the param `-Dkubernetes.container.image.pull-policy=Always` into `Dynamic Option`. otherwise , the k 8s would not pull the last version from docker responsitory.

thx, i will add it

**Comment by xinzhuxiansheng** [comment]
"-Dkubernetes.container.image.pull-policy=Always"  Unable to resolve the problem,  i don't see new image in harbor. there is only one 。

![图片](https://user-images.githubusercontent.com/7881241/144958506-c5f17332-c8c7-4c5c-affa-9a72660fbc2f.png)
