### ISSUE TITLE
[Bug] init ddl sql error.

### ISSUE THREAD

**Issue by t291436520** [streamxhub/streamx#501]
*Please answer these questions before submitting your issue. Thanks!*

### 

* **StreamX Version**:  main
* **JVM version** (`java -version`): java11
* **OS version** (`uname -a` if on a Unix-like system):

### Bug Description
我看文档上面配置项说 《特别提示: 安装过程中不需要手动做数据初始化，只需要设置好数据库信息即可，会自动完成建表和数据初始化等一些列操作》 但是我启动后 并没有自动创建项目相关的业务表

**Comment by wolfboys** [comment]
after 1.2.1,need to execute ddl sql by yourself.
