### ISSUE TITLE
[Bug]  When adding a job,  The form verification does not call back

### ISSUE THREAD

**Issue by xinzhuxiansheng** [streamxhub/streamx#505]
*Please answer these questions before submitting your issue. Thanks!*

### Environment Description
* **StreamX Version**:  main branch
* **JVM version** (`java -version`):
* **OS version** (`uname -a` if on a Unix-like system):

### How to Reproduce 
Steps to reproduce the behavior, for example:

### Additional context
Add any other context about the problem here such as JVM track stack log.

### Requirement or improvement

- Please describe about your requirements or improvement suggestions.
- 
In the add job form item "Execution Mode" select "kubernetes application", fill in other information, finally the form verification does not call back

**Comment by wolfboys** [comment]
u can fix this bug.😊👍

**Comment by xinzhuxiansheng** [comment]
> u can fix this bug.😊👍

I have submitted a PR to fix this problem  https://github.com/streamxhub/streamx/pull/503

**Comment by wolfboys** [comment]
> > u can fix this bug.😊👍
> 
> I have submitted a PR to fix this problem #503

u can close this issue.

**Comment by xinzhuxiansheng** [comment]
> > > u can fix this bug.😊👍
> > 
> > 
> > I have submitted a PR to fix this problem #503
> 
> u can close this issue.

thanks  :)
