### ISSUE TITLE
StreamXConsole 启动的时候空指针异常

### ISSUE THREAD

**Issue by johncai0** [streamxhub/streamx#515]
错误日志如下
![image](https://user-images.githubusercontent.com/20558180/145672506-5a53e416-2411-4b31-bd95-76df4d06d324.png)

对应的代码在
com.streamxhub.streamx.console.base.util.WebUtils#getAppHome

![image](https://user-images.githubusercontent.com/20558180/145672541-5b002f75-d5d3-4abc-bb3c-17d7f0c7a6a4.png)

问题是我的环境中app.home 这个目录应该设置到什么地方？这个应该是web页面的路径吧？

**Comment by xinzhuxiansheng** [comment]
@johncai0   configuration vm options in idea, please refer to the document  . http://www.streamxhub.com/doc/console/deployment/#vm-options

**Comment by wolfboys** [comment]
see: #507

**Comment by yimingtech** [comment]
http://www.streamxhub.com/doc/console/deployment/#vm-options 链接打不开了，失效了

**Comment by liyichencc** [comment]
> http://www.streamxhub.com/doc/console/deployment/#vm-options 链接打不开了，失效了

Now you can refer to this address: https://streampark.apache.org/zh-CN/docs/user-guide/deployment/
