### ISSUE TITLE
windows idea要怎么运行

### ISSUE THREAD

**Issue by zhihui-ge** [streamxhub/streamx#95]

**Comment by boliza** [comment]
你的问题是什么？

**Comment by zhihui-ge** [comment]
windows下用idea把项目跑起来，然后调试

**Comment by hhaiben123** [comment]
![image](https://user-images.githubusercontent.com/10437011/115486697-c8527b00-a289-11eb-8837-5f3e308e2ec6.png)
编译的时候有问题
