### ISSUE TITLE
任务提交后一直显示  DEPLOYING ，点击圆圈看不到日志，后台日志没有报错

### ISSUE THREAD

**Issue by dwave** [streamxhub/streamx#98]
![image](https://user-images.githubusercontent.com/14970783/114643668-b5c7c700-9d08-11eb-9e8a-21d6b1cf62e7.png)
![image](https://user-images.githubusercontent.com/14970783/114643684-beb89880-9d08-11eb-87d3-5f7851cda6ae.png)
部署中的任务不知道在哪里能停止，

其中自己创建的任务点进去后报错
![image](https://user-images.githubusercontent.com/14970783/114643859-0b03d880-9d09-11eb-855d-ad59a99eda23.png)

**Comment by wolfboys** [comment]
thanks. already fixed!
